name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i --prefix docs
      - name: Install prerequisites and test
        run: npm run build --prefix docs
  lib:
    runs-on: ubuntu-latest
    strategy:
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: [16.x]
      - run: npm i
      - run: npm run lint
      - run: npm test
